apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: thmmth/backend:latest # Immagine Docker Hub
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/socialDashboard"
        - name: INSTAGRAM_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              name: instagram-config
              key: INSTAGRAM_ACCESS_TOKEN
